  var VI_TO_EN_BREEDS = {
    "Không xác định": "Not determined",
    "Chó Không xác định": "Unknown",
    "Shiba": "Shiba Dog",
    "Chó Shiba": "Shiba Dog",
    "Bulldog Pháp": "French Bulldog",
    "Chó Bulldog Pháp": "French Bulldog",
    "Husky Siberia": "Siberian Husky",
    "Chó Husky Siberia": "Siberian Husky",
    "Alaska Malamute": "Malamute",
    "Chó Alaska Malamute": "Malamute",
    "Phốc sóc": "Pomeranian",
    "Corgi Pembroke": "Pembroke",
    "Chó Corgi Pembroke": "Pembroke",
    "Corgi Cardigan": "Cardigan",
    "Chó Corgi Cardigan": "Cardigan",
    "Béc-giê Đức": "German Shepherd",
    "Labrador": "Labrador Retriever",
    "Chó Labrador": "Labrador Retriever",
    "Golden": "Golden Retriever",
    "Chó Golden": "Golden Retriever",
    "Chihuahua": "Chihuahua",
    "Chó Chihuahua": "Chihuahua",
    "Pug": "Pug",
    "Chó Pug": "Pug",
    "Shih Tzu": "Shih Tzu",
    "Chó Shih Tzu": "Shih Tzu",
    "Maltese": "Maltese Dog",
    "Chó Maltese": "Maltese Dog",
    "Bắc Kinh": "Pekinese",
    "Chó Bắc Kinh": "Pekinese",
    "Papillon": "Papillon",
    "Chó Papillon": "Papillon",
    "Phốc hươu": "Miniature Pinscher",
    "Boston Terrier": "Boston Bull",
    "Chó Boston Terrier": "Boston Bull",
    "Boxer": "Boxer",
    "Chó Boxer": "Boxer",
    "Bichon Frise": "Bichon Frise",
    "Chó Bichon Frise": "Bichon Frise",
    "Chow Chow": "Chow",
    "Chó Chow Chow": "Chow",
    "Rottweiler": "Rottweiler",
    "Chó Rottweiler": "Rottweiler",
    "Doberman": "Doberman",
    "Chó Doberman": "Doberman",
    "Saint Bernard": "Saint Bernard",
    "Chó Saint Bernard": "Saint Bernard",
    "Samoyed": "Samoyed",
    "Chó Samoyed": "Samoyed",
    "Ngao Tây Tạng": "Tibetan Mastiff",
    "Ngao Đức": "Great Dane",
    "Great Pyrenees": "Great Pyrenees",
    "Chó Great Pyrenees": "Great Pyrenees",
    "Bullmastiff": "Bull Mastiff",
    "Chó Bullmastiff": "Bull Mastiff",
    "Poodle Mini": "Miniature Poodle",
    "Chó Poodle Mini": "Miniature Poodle",
    "Poodle Toy": "Toy Poodle",
    "Chó Poodle Toy": "Toy Poodle",
    "Poodle Standard": "Standard Poodle",
    "Chó Poodle Standard": "Standard Poodle",
    "Schnauzer Mini": "Miniature Schnauzer",
    "Chó Schnauzer Mini": "Miniature Schnauzer",
    "Schnauzer Standard": "Standard Schnauzer",
    "Chó Schnauzer Standard": "Standard Schnauzer",
    "Schnauzer Giant": "Giant Schnauzer",
    "Chó Schnauzer Giant": "Giant Schnauzer",
    "Westie": "West Highland White Terrier",
    "Chó Westie": "West Highland White Terrier",
    "Amstaff": "American Staffordshire Terrier",
    "Chó Amstaff": "American Staffordshire Terrier",
    "Staffordshire Bull Terrier": "Staffordshire Bullterrier",
    "Chó Staffordshire Bull Terrier": "Staffordshire Bullterrier",
    "Scottie": "Scotch Terrier",
    "Chó Scottie": "Scotch Terrier",
    "Yorkshire Terrier": "Yorkshire Terrier",
    "Chó Yorkshire Terrier": "Yorkshire Terrier",
    "Basset Hound": "Basset",
    "Chó Basset Hound": "Basset",
    "Beagle": "Beagle",
    "Chó Beagle": "Beagle",
    "Cocker": "Cocker Spaniel",
    "Chó Cocker": "Cocker Spaniel",
    "Cavalier King Charles (Blenheim)": "Blenheim Spaniel",
    "Chó Cavalier King Charles (Blenheim)": "Blenheim Spaniel",
    "Springer Anh": "English Springer",
    "Chó Springer Anh": "English Springer",
    "Springer xứ Wales": "Welsh Springer Spaniel",
    "Chó Springer xứ Wales": "Welsh Springer Spaniel",
    "Irish Setter": "Irish Setter",
    "Chó Irish Setter": "Irish Setter",
    "Setter Anh": "English Setter",
    "Chó Setter Anh": "English Setter",
    "Irish Terrier": "Irish Terrier",
    "Chó Irish Terrier": "Irish Terrier",
    "Gordon Setter": "Gordon Setter",
    "Chó Gordon Setter": "Gordon Setter",
    "Pointer Đức": "German Short Haired Pointer",
    "Chó Pointer Đức": "German Short Haired Pointer",
    "Chesapeake Retriever": "Chesapeake Bay Retriever",
    "Chó Chesapeake Retriever": "Chesapeake Bay Retriever",
    "Curly-coated Retriever": "Curly Coated Retriever",
    "Chó Curly-coated Retriever": "Curly Coated Retriever",
    "Flat-coated Retriever": "Flat Coated Retriever",
    "Chó Flat-coated Retriever": "Flat Coated Retriever",
    "Sheltie": "Shetland Sheepdog",
    "Chó Sheltie": "Shetland Sheepdog",
    "Border Collie": "Border Collie",
    "Chó Border Collie": "Border Collie",
    "Bobtail": "Old English Sheepdog",
    "Chó Bobtail": "Old English Sheepdog",
    "Béc-giê Bỉ Malinois": "Malinois",
    "Béc-giê Bỉ Groenendael": "Groenendael",
    "Cane Corso": "Cane Corso",
    "Chó Cane Corso": "Cane Corso",
    "Fila Brasileiro": "Fila Brasileiro",
    "Chó Fila Brasileiro": "Fila Brasileiro",
    "Chó mào Trung Quốc": "Chinese Crested Dog",
    "Chó cỏ Trung Quốc": "Chinese Rural Dog",
    "Mexican Hairless": "Mexican Hairless",
    "Chó Mexican Hairless": "Mexican Hairless",
    "Chó ta Việt Nam": "Vietnamese Native Dog",
    "Chó Bắc Hà": "Bac Ha Dog",
    "Chó H'Mông cộc đuôi": "Hmong Bobtail Dog",
    "Teddy": "Teddy",
    "Chó Teddy": "Teddy",
    "Black and Tan Coonhound": "Black and Tan Coonhound",
    "Chó Black and Tan Coonhound": "Black and Tan Coonhound",
    "Bluetick Coonhound": "Bluetick",
    "Chó Bluetick Coonhound": "Bluetick",
    "Redbone Coonhound": "Redbone",
    "Chó Redbone Coonhound": "Redbone",
    "Treeing Walker Coonhound": "Walker Hound",
    "Chó Treeing Walker Coonhound": "Walker Hound",
    "Airedale Terrier": "Airedale",
    "Chó Airedale Terrier": "Airedale",
    "Border Terrier": "Border Terrier",
    "Chó Border Terrier": "Border Terrier",
    "Norwich Terrier": "Norwich Terrier",
    "Chó Norwich Terrier": "Norwich Terrier",
    "Norfolk Terrier": "Norfolk Terrier",
    "Chó Norfolk Terrier": "Norfolk Terrier",
    "Lakeland Terrier": "Lakeland Terrier",
    "Chó Lakeland Terrier": "Lakeland Terrier",
    "Bedlington Terrier": "Bedlington Terrier",
    "Chó Bedlington Terrier": "Bedlington Terrier",
    "Sealyham Terrier": "Sealyham Terrier",
    "Chó Sealyham Terrier": "Sealyham Terrier",
    "Silky Terrier": "Silky Terrier",
    "Chó Silky Terrier": "Silky Terrier",
    "Toy Terrier": "Toy Terrier",
    "Chó Toy Terrier": "Toy Terrier",
    "Kerry Blue Terrier": "Kerry Blue Terrier",
    "Chó Kerry Blue Terrier": "Kerry Blue Terrier",
    "Wire Fox Terrier": "Wire Haired Fox Terrier",
    "Chó Wire Fox Terrier": "Wire Haired Fox Terrier",
    "Wheaten Terrier": "Soft Coated Wheaten Terrier",
    "Chó Wheaten Terrier": "Soft Coated Wheaten Terrier",
    "Elkhound Na Uy": "Norwegian Elkhound",
    "Chó Elkhound Na Uy": "Norwegian Elkhound",
    "Ridgeback Rhodesia": "Rhodesian Ridgeback",
    "Chó Ridgeback Rhodesia": "Rhodesian Ridgeback",
    "Irish Wolfhound": "Irish Wolfhound",
    "Chó Irish Wolfhound": "Irish Wolfhound",
    "Deerhound Scotland": "Scottish Deerhound",
    "Chó Deerhound Scotland": "Scottish Deerhound",
    "Greyhound Ý": "Italian Greyhound",
    "Chó Greyhound Ý": "Italian Greyhound",
    "Whippet": "Whippet",
    "Chó Whippet": "Whippet",
    "Borzoi": "Borzoi",
    "Chó Borzoi": "Borzoi",
    "Afghan Hound": "Afghan Hound",
    "Chó Afghan Hound": "Afghan Hound",
    "Saluki": "Saluki",
    "Chó Saluki": "Saluki",
    "Ibizan Hound": "Ibizan Hound",
    "Chó Ibizan Hound": "Ibizan Hound",
    "Vizsla": "Vizsla",
    "Chó Vizsla": "Vizsla",
    "Weimaraner": "Weimaraner",
    "Chó Weimaraner": "Weimaraner",
    "Otterhound": "Otterhound",
    "Chó Otterhound": "Otterhound",
    "Bloodhound": "Bloodhound",
    "Chó Bloodhound": "Bloodhound",
    "Foxhound Anh": "English Foxhound",
    "Chó Foxhound Anh": "English Foxhound",
    "Chin Nhật": "Japanese Spaniel",
    "Chó Chin Nhật": "Japanese Spaniel",
    "Spitz Nhật": "Japanese Spitz",
    "Chó Spitz Nhật": "Japanese Spitz",
    "Eskimo Mỹ": "Eskimo Dog",
    "Chó Eskimo Mỹ": "Eskimo Dog",
    "Keeshond": "Keeshond",
    "Chó Keeshond": "Keeshond",
    "Newfoundland": "Newfoundland",
    "Chó Newfoundland": "Newfoundland",
    "Bernese Mountain Dog": "Bernese Mountain Dog",
    "Chó Bernese Mountain Dog": "Bernese Mountain Dog",
    "Greater Swiss Mountain Dog": "Greater Swiss Mountain Dog",
    "Chó Greater Swiss Mountain Dog": "Greater Swiss Mountain Dog",
    "Entlebucher": "Entlebucher",
    "Chó Entlebucher": "Entlebucher",
    "Appenzeller": "Appenzeller",
    "Chó Appenzeller": "Appenzeller",
    "Kuvasz": "Kuvasz",
    "Chó Kuvasz": "Kuvasz",
    "Komondor": "Komondor",
    "Chó Komondor": "Komondor",
    "Leonberger": "Leonberg",
    "Chó Leonberger": "Leonberg",
    "Lhasa": "Lhasa",
    "Chó Lhasa": "Lhasa",
    "Dandie Dinmont Terrier": "Dandie Dinmont",
    "Chó Dandie Dinmont Terrier": "Dandie Dinmont",
    "Schipperke": "Schipperke",
    "Chó Schipperke": "Schipperke",
    "Affenpinscher": "Affenpinscher",
    "Chó Affenpinscher": "Affenpinscher",
    "Basenji": "Basenji",
    "Chó Basenji": "Basenji",
    "Dhole": "Dhole",
    "Chó Dhole": "Dhole",
    "Dingo": "Dingo",
    "Chó Dingo": "Dingo",
    "Chó hoang châu Phi": "African Hunting Dog",
    "Briard": "Briard",
    "Chó Briard": "Briard",
    "Collie": "Collie",
    "Chó Collie": "Collie",
    "Shepherd Úc": "Australian Shepherd",
    "Chó Shepherd Úc": "Australian Shepherd",
    "Terrier Úc": "Australian Terrier",
    "Chó Terrier Úc": "Australian Terrier",
    "Bouvier des Flandres": "Bouvier des Flandres",
    "Chó Bouvier des Flandres": "Bouvier des Flandres",
    "Brussels Griffon": "Brabancon Griffon",
    "Chó Brussels Griffon": "Brabancon Griffon",
    "Kelpie": "Kelpie",
    "Chó Kelpie": "Kelpie",
    "Clumber Spaniel": "Clumber",
    "Chó Clumber Spaniel": "Clumber",
    "Irish Water Spaniel": "Irish Water Spaniel",
    "Chó Irish Water Spaniel": "Irish Water Spaniel",
    "Brittany Spaniel": "Brittany Spaniel",
    "Chó Brittany Spaniel": "Brittany Spaniel",
    "Sussex Spaniel": "Sussex Spaniel",
    "Chó Sussex Spaniel": "Sussex Spaniel",
    "Terrier Tây Tạng": "Tibetan Terrier",
    "Chó Terrier Tây Tạng": "Tibetan Terrier",
    "Cairn Terrier": "Cairn",
    "Chó Cairn Terrier": "Cairn",
    "Chưa xác định": "Not determined"
};
